### ISSUE TITLE
Расписание 4 курса 

### ISSUE THREAD

**Issue by Delivery-Klad** [mirea-ninja/university-app#227]
**Описание ошибки**
На 9 неделе у 4 курса все еще показывается учебное расписание

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Быть на 4 курсе

**Ожидаемое поведение**
Не отображать учебное расписание или отображать расписание сессии

**Смартфон:**
 - Девайс: iPhone7
 - OS: iOS15.1
 - Браузер stock browser, safari

**Comment by 0niel** [comment]
Спасибо! О проблеме знаем, будем решать на стороне сервера.
