### ISSUE TITLE
Поиск аудитории

### ISSUE THREAD

**Issue by lokot0k** [mirea-ninja/university-app#244]
Мне, как первокурснику, сложно ориентироваться в вузе и очень не хватает функции поиска аудитории, ведь первая цифра в номерах аудиторий может не соответствовать этажу, аудитории иногда расположены не по порядку. 

Хочется видеть функцию поиска в разделе "Карты", которая будет открывать нужный этаж и подсвечивать нужную аудиторию. Одним из возможных решений будет хранение периметров аудиторий, их названий и этажей. Пользователь вводит название аудитории -> периметр достается из мапы/бд -> открывается нужный этаж -> сектор внутри периметра меняет цвет(или любое другое выделение)

Думаю, это очень помогло бы, ведь не придется вручную искать аудиторию на нескольких этажах (что особенно критично когда перемена 10 минут, а на паре задержали на 5 минут и нужно быстро найти и дойти до аудитории)

**Comment by Dragonprod** [comment]
Привет, данный функционал запланирован в обновлении.
