### ISSUE TITLE
Версия для ПК

### ISSUE THREAD

**Issue by ExxRyan** [mirea-ninja/university-app#339]
**Связан ли ваш запрос на функцию с проблемой? Пожалуйста, опишите.**
Нет.

**Опишите решение, которое вы хотели бы**
Было бы круто добавить версию для ПК. Даже на 1 курсе на своем потоке я вижу довольно большое количество людей с ноутбуками. Было бы классно собирать Flutter-приложение для Windows и Linux. 

**Опишите альтернативы, которые вы рассматривали**
Можно запускать .apk через эмулятор BlueStacks, но выглядит это довольно грустно, из-за того что у приложения нет поддержки горизонтального режима
![image](https://github.com/mirea-ninja/university-app/assets/94524319/29435b50-edc5-493d-b32f-651d6eadfc1a)

да и на телефоне он сильно не нужен.

**Дополнительный текст**
Нет.

**Comment by 0niel** [comment]
Привет. Версия для Windows доступна для скачивания со страницы релизов. https://github.com/mirea-ninja/university-app/releases/download/1.3.5/windows.zip

Версию для Linux у меня пока что нет возможности компилировать. Возможно, сделаю это через Workflow гитхаба.

![image](https://github.com/mirea-ninja/university-app/assets/51058739/df449768-9724-4dca-a45e-35ffac19f3a0)

**Comment by ExxRyan** [comment]
Кул! Тогда удачи в разработке, ждем версию под Linux, ишью закрываю)
